name: FHIR Connectathon Issue
description: Report an issue encountered during the FHIR Connectathon
title: "[Connectathon] "
labels: ["Connectathon"]
body:
  - type: dropdown
    id: resource
    attributes:
      label: FHIR Resource
      description: Select the FHIR resource related to the issue
      options:
        - Patient
        - Encounter
        - Condition
        - Medication
        - Observation
    validations:
      required: true

  - type: dropdown
    id: activity
    attributes:
      label: Activity
      description: What activity were you performing?
      options:
        - Create
        - Update
        - Validate
        - Search
        - Other
    validations:
      required: true

  - type: textarea
    id: comments
    attributes:
      label: Comments
      description: Provide any additional details about the issue
      placeholder: Describe the issue, steps to reproduce, expected vs actual behavior, etc.
    validations:
      required: false
